---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: example-chart-hr
  namespace: flux-system
spec:
  chart:
    spec:
      chart: example-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: source-helm
  interval: 1m0s
  targetNamespace: 5-demo
