---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: 5-demo-helm-release-git-helm-bb-app-exple-chart
  namespace: flux-system
spec:
  chart:
    spec:
      chart: example-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: 5-demo-source-git-helm-bb-app-exple-chart
  interval: 10s
  targetNamespace: 5-demo
